# Compilation of scord and execution of tests

image: bscstorage/scord:0.2.0-wip

stages:
  - build
  - test

gcc-release:
  stage: build
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
    - mkdir -p build
    - cd build
    - cmake
      -DCMAKE_BUILD_TYPE:STRING=Release
      -DCMAKE_PREFIX_PATH:STRING=/usr/local
      -DCMAKE_INSTALL_PREFIX:STRING=${CI_PROJECT_DIR}/compiled
      -DSCORD_BUILD_EXAMPLES:BOOL=ON
      -DSCORD_BUILD_TESTS:BOOL=ON
      -DSCORD_TRANSPORT_LIBRARY=libfabric
      -DSCORD_TRANSPORT_PROTOCOL=ofi+tcp
      -DSCORD_BIND_ADDRESS=127.0.0.1
      -DSCORD_BIND_PORT=52000
      ..
    - make -j$(nproc) install

gcc-debug:
  stage: build
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
    - mkdir -p build
    - cd build
    - cmake
      -DCMAKE_BUILD_TYPE:STRING=Debug
      -DCMAKE_PREFIX_PATH:STRING=/usr/local
      -DCMAKE_INSTALL_PREFIX:STRING=${CI_PROJECT_DIR}/compiled
      -DSCORD_BUILD_EXAMPLES:BOOL=ON
      -DSCORD_BUILD_TESTS:BOOL=ON
      -DSCORD_TRANSPORT_LIBRARY=libfabric
      -DSCORD_TRANSPORT_PROTOCOL=ofi+tcp
      -DSCORD_BIND_ADDRESS=127.0.0.1
      -DSCORD_BIND_PORT=52000
      ..
    - make -j$(nproc) install
  artifacts:
    expire_in: 2 days
    paths:
      - compiled/bin/
      - compiled/etc/
      - compiled/lib/
      - build/examples/
      - build/tests/
      - build/src/scord/scord
      - build/src/scord-ctl/scord-ctl

clang:
  stage: build
  parallel:
    matrix:
      - CMAKE_BUILD_TYPE: [ Debug, Release ]
  script:
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
    - mkdir -p build
    - cd build
    - cmake
      -DCMAKE_CXX_COMPILER=/usr/bin/clang++
      -DCMAKE_C_COMPILER=/usr/bin/clang
      -DCMAKE_PREFIX_PATH:STRING=/usr/local
      -DCMAKE_INSTALL_PREFIX:STRING=${CI_PROJECT_DIR}/compiled
      -DSCORD_BUILD_EXAMPLES:BOOL=ON
      -DSCORD_BUILD_TESTS:BOOL=ON
      -DSCORD_TRANSPORT_LIBRARY=libfabric
      -DSCORD_TRANSPORT_PROTOCOL=ofi+tcp
      -DSCORD_BIND_ADDRESS=127.0.0.1
      -DSCORD_BIND_PORT=52000
      ..
    - make -j$(nproc) install

# run RPC tests using the binary built before
rpc:
  stage: test
  needs: [ gcc-debug ]
  script:
    - export ASAN_OPTIONS=detect_odr_violation=0:detect_leaks=0
    - export LSAN_OPTIONS=verbosity=1:log_threads=1:suppressions=${CI_PROJECT_DIR}/tests/LSanSuppress.supp
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:${CI_PROJECT_DIR}/compiled/lib
    - cd build/examples/
    - ctest -j$(nproc) --output-on-failure --output-junit rpc-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - build/examples/rpc-report.xml
    reports:
      junit: build/examples/rpc-report.xml

# run unit tests
unit:
  stage: test
  needs: [ gcc-debug ]
  script:
    - export ASAN_OPTIONS=detect_odr_violation=0
    - export LSAN_OPTIONS=verbosity=1:log_threads=1:suppressions=${CI_PROJECT_DIR}/tests/LSanSuppress.supp
    - export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64:${CI_PROJECT_DIR}/compiled/lib
    - cd build/tests
    - ctest -j$(nproc) --output-on-failure --output-junit unit-report.xml
  artifacts:
    expire_in: 1 week
    paths:
      - build/tests/unit-report.xml
    reports:
      junit: build/tests/unit-report.xml
