sections:
  - name: "global_settings"
    required: true
    options:
      - name: "use_syslog"
        required: true
        type: "bool"
        converter: "parsers::parse_bool"

      - name: "log_file"
        required: false
        type: "std::filesystem::path"
        converter: "parsers::parse_path"

      - name: "log_file_max_size"
        required: false
        type: "uint32_t"
        converter: "parsers::parse_capacity"

      - name: "transport_protocol"
        required: true
        type: "std::string"

      - name: "bind_address"
        required: true
        type: "std::string"

      - name: "remote_port"
        required: true
        type: "uint32_t"
        converter: "parsers::parse_number"

      - name: "pidfile"
        required: true
        type: "std::filesystem::path"
        converter: "parsers::parse_path"

      - name: "workers"
        required: true
        type: "uint32_t"
        converter: "parsers::parse_number"
